package com.photoeditor.editor.filter;

/**
 * GLSL shader source code for the photo editor filter pipeline.
 * Ported from Telegram's FilterShaders.java (GPL v2).
 */
public final class FilterShaders {

    private FilterShaders() {}

    public static final String SIMPLE_VERTEX = ""
            + "attribute vec4 position;\n"
            + "attribute vec2 inputTexCoord;\n"
            + "varying vec2 vTextureCoord;\n"
            + "void main() {\n"
            + "    gl_Position = position;\n"
            + "    vTextureCoord = inputTexCoord;\n"
            + "}\n";

    public static final String SIMPLE_FRAGMENT = ""
            + "varying highp vec2 vTextureCoord;\n"
            + "uniform sampler2D sTexture;\n"
            + "void main() {\n"
            + "    gl_FragColor = texture2D(sTexture, vTextureCoord);\n"
            + "}\n";

    public static final String SHARPEN_VERTEX = ""
            + "attribute vec4 position;\n"
            + "attribute vec2 inputTexCoord;\n"
            + "varying vec2 vTextureCoord;\n"
            + "uniform highp float inputWidth;\n"
            + "uniform highp float inputHeight;\n"
            + "varying vec2 leftTexCoord;\n"
            + "varying vec2 rightTexCoord;\n"
            + "varying vec2 topTexCoord;\n"
            + "varying vec2 bottomTexCoord;\n"
            + "void main() {\n"
            + "    gl_Position = position;\n"
            + "    vTextureCoord = inputTexCoord;\n"
            + "    highp vec2 widthStep = vec2(1.0 / inputWidth, 0.0);\n"
            + "    highp vec2 heightStep = vec2(0.0, 1.0 / inputHeight);\n"
            + "    leftTexCoord = inputTexCoord - widthStep;\n"
            + "    rightTexCoord = inputTexCoord + widthStep;\n"
            + "    topTexCoord = inputTexCoord + heightStep;\n"
            + "    bottomTexCoord = inputTexCoord - heightStep;\n"
            + "}\n";

    public static final String SHARPEN_FRAGMENT = ""
            + "precision highp float;\n"
            + "varying vec2 vTextureCoord;\n"
            + "varying vec2 leftTexCoord;\n"
            + "varying vec2 rightTexCoord;\n"
            + "varying vec2 topTexCoord;\n"
            + "varying vec2 bottomTexCoord;\n"
            + "uniform sampler2D sTexture;\n"
            + "uniform float sharpen;\n"
            + "void main() {\n"
            + "    vec4 result = texture2D(sTexture, vTextureCoord);\n"
            + "    vec3 leftTextureColor = texture2D(sTexture, leftTexCoord).rgb;\n"
            + "    vec3 rightTextureColor = texture2D(sTexture, rightTexCoord).rgb;\n"
            + "    vec3 topTextureColor = texture2D(sTexture, topTexCoord).rgb;\n"
            + "    vec3 bottomTextureColor = texture2D(sTexture, bottomTexCoord).rgb;\n"
            + "    result.rgb = result.rgb * (1.0 + 4.0 * sharpen) - (leftTextureColor + rightTextureColor + topTextureColor + bottomTextureColor) * sharpen;\n"
            + "    gl_FragColor = result;\n"
            + "}\n";

    public static final String TOOLS_FRAGMENT = ""
            + "varying highp vec2 vTextureCoord;\n"
            + "uniform sampler2D sTexture;\n"
            + "uniform highp float width;\n"
            + "uniform highp float height;\n"
            + "uniform sampler2D curvesImage;\n"
            + "uniform lowp float skipTone;\n"
            + "uniform lowp float shadows;\n"
            + "const mediump vec3 hsLuminanceWeighting = vec3(0.3, 0.3, 0.3);\n"
            + "uniform lowp float highlights;\n"
            + "uniform lowp float contrast;\n"
            + "uniform lowp float fadeAmount;\n"
            + "const mediump vec3 satLuminanceWeighting = vec3(0.2126, 0.7152, 0.0722);\n"
            + "uniform lowp float saturation;\n"
            + "uniform lowp float shadowsTintIntensity;\n"
            + "uniform lowp float highlightsTintIntensity;\n"
            + "uniform lowp vec3 shadowsTintColor;\n"
            + "uniform lowp vec3 highlightsTintColor;\n"
            + "uniform lowp float exposure;\n"
            + "uniform lowp float warmth;\n"
            + "uniform lowp float grain;\n"
            + "const lowp float permTexUnit = 1.0 / 256.0;\n"
            + "const lowp float permTexUnitHalf = 0.5 / 256.0;\n"
            + "const lowp float grainsize = 2.3;\n"
            + "uniform lowp float vignette;\n"
            + "\n"
            + "highp float getLuma(highp vec3 rgbP) {\n"
            + "    return (0.299 * rgbP.r) + (0.587 * rgbP.g) + (0.114 * rgbP.b);\n"
            + "}\n"
            + "\n"
            + "lowp vec3 rgbToHsv(lowp vec3 c) {\n"
            + "    highp vec4 K = vec4(0.0, -1.0 / 3.0, 2.0 / 3.0, -1.0);\n"
            + "    highp vec4 p = c.g < c.b ? vec4(c.bg, K.wz) : vec4(c.gb, K.xy);\n"
            + "    highp vec4 q = c.r < p.x ? vec4(p.xyw, c.r) : vec4(c.r, p.yzx);\n"
            + "    highp float d = q.x - min(q.w, q.y);\n"
            + "    highp float e = 1.0e-10;\n"
            + "    return vec3(abs(q.z + (q.w - q.y) / (6.0 * d + e)), d / (q.x + e), q.x);\n"
            + "}\n"
            + "\n"
            + "lowp vec3 hsvToRgb(lowp vec3 c) {\n"
            + "    highp vec4 K = vec4(1.0, 2.0 / 3.0, 1.0 / 3.0, 3.0);\n"
            + "    highp vec3 p = abs(fract(c.xxx + K.xyz) * 6.0 - K.www);\n"
            + "    return c.z * mix(K.xxx, clamp(p - K.xxx, 0.0, 1.0), c.y);\n"
            + "}\n"
            + "\n"
            + "highp vec3 rgbToHsl(highp vec3 color) {\n"
            + "    highp vec3 hsl;\n"
            + "    highp float fmin = min(min(color.r, color.g), color.b);\n"
            + "    highp float fmax = max(max(color.r, color.g), color.b);\n"
            + "    highp float delta = fmax - fmin;\n"
            + "    hsl.z = (fmax + fmin) / 2.0;\n"
            + "    if (delta == 0.0) {\n"
            + "        hsl.x = 0.0;\n"
            + "        hsl.y = 0.0;\n"
            + "    } else {\n"
            + "        if (hsl.z < 0.5) {\n"
            + "            hsl.y = delta / (fmax + fmin);\n"
            + "        } else {\n"
            + "            hsl.y = delta / (2.0 - fmax - fmin);\n"
            + "        }\n"
            + "        highp float deltaR = (((fmax - color.r) / 6.0) + (delta / 2.0)) / delta;\n"
            + "        highp float deltaG = (((fmax - color.g) / 6.0) + (delta / 2.0)) / delta;\n"
            + "        highp float deltaB = (((fmax - color.b) / 6.0) + (delta / 2.0)) / delta;\n"
            + "        if (color.r == fmax) {\n"
            + "            hsl.x = deltaB - deltaG;\n"
            + "        } else if (color.g == fmax) {\n"
            + "            hsl.x = (1.0 / 3.0) + deltaR - deltaB;\n"
            + "        } else if (color.b == fmax) {\n"
            + "            hsl.x = (2.0 / 3.0) + deltaG - deltaR;\n"
            + "        }\n"
            + "        if (hsl.x < 0.0) {\n"
            + "            hsl.x += 1.0;\n"
            + "        } else if (hsl.x > 1.0) {\n"
            + "            hsl.x -= 1.0;\n"
            + "        }\n"
            + "    }\n"
            + "    return hsl;\n"
            + "}\n"
            + "\n"
            + "highp float hueToRgb(highp float f1, highp float f2, highp float hue) {\n"
            + "    if (hue < 0.0) { hue += 1.0; }\n"
            + "    else if (hue > 1.0) { hue -= 1.0; }\n"
            + "    highp float res;\n"
            + "    if ((6.0 * hue) < 1.0) { res = f1 + (f2 - f1) * 6.0 * hue; }\n"
            + "    else if ((2.0 * hue) < 1.0) { res = f2; }\n"
            + "    else if ((3.0 * hue) < 2.0) { res = f1 + (f2 - f1) * ((2.0 / 3.0) - hue) * 6.0; }\n"
            + "    else { res = f1; }\n"
            + "    return res;\n"
            + "}\n"
            + "\n"
            + "highp vec3 hslToRgb(highp vec3 hsl) {\n"
            + "    if (hsl.y == 0.0) {\n"
            + "        return vec3(hsl.z);\n"
            + "    } else {\n"
            + "        highp float f2;\n"
            + "        if (hsl.z < 0.5) { f2 = hsl.z * (1.0 + hsl.y); }\n"
            + "        else { f2 = (hsl.z + hsl.y) - (hsl.y * hsl.z); }\n"
            + "        highp float f1 = 2.0 * hsl.z - f2;\n"
            + "        return vec3(hueToRgb(f1, f2, hsl.x + (1.0/3.0)), hueToRgb(f1, f2, hsl.x), hueToRgb(f1, f2, hsl.x - (1.0/3.0)));\n"
            + "    }\n"
            + "}\n"
            + "\n"
            + "highp vec3 rgbToYuv(highp vec3 inP) {\n"
            + "    highp float luma = getLuma(inP);\n"
            + "    return vec3(luma, (1.0 / 1.772) * (inP.b - luma), (1.0 / 1.402) * (inP.r - luma));\n"
            + "}\n"
            + "\n"
            + "lowp vec3 yuvToRgb(highp vec3 inP) {\n"
            + "    return vec3(1.402 * inP.b + inP.r, (inP.r - (0.299 * 1.402 / 0.587) * inP.b - (0.114 * 1.772 / 0.587) * inP.g), 1.772 * inP.g + inP.r);\n"
            + "}\n"
            + "\n"
            + "lowp float easeInOutSigmoid(lowp float value, lowp float strength) {\n"
            + "    if (value > 0.5) {\n"
            + "        return 1.0 - pow(2.0 - 2.0 * value, 1.0 / (1.0 - strength)) * 0.5;\n"
            + "    } else {\n"
            + "        return pow(2.0 * value, 1.0 / (1.0 - strength)) * 0.5;\n"
            + "    }\n"
            + "}\n"
            + "\n"
            + "lowp vec3 applyLuminanceCurve(lowp vec3 pixel) {\n"
            + "    highp float index = floor(clamp(pixel.z / (1.0 / 200.0), 0.0, 199.0));\n"
            + "    pixel.y = mix(0.0, pixel.y, smoothstep(0.0, 0.1, pixel.z) * (1.0 - smoothstep(0.8, 1.0, pixel.z)));\n"
            + "    pixel.z = texture2D(curvesImage, vec2(1.0 / 200.0 * index, 0)).a;\n"
            + "    return pixel;\n"
            + "}\n"
            + "\n"
            + "lowp vec3 applyRGBCurve(lowp vec3 pixel) {\n"
            + "    highp float index = floor(clamp(pixel.r / (1.0 / 200.0), 0.0, 199.0));\n"
            + "    pixel.r = texture2D(curvesImage, vec2(1.0 / 200.0 * index, 0)).r;\n"
            + "    index = floor(clamp(pixel.g / (1.0 / 200.0), 0.0, 199.0));\n"
            + "    pixel.g = clamp(texture2D(curvesImage, vec2(1.0 / 200.0 * index, 0)).g, 0.0, 1.0);\n"
            + "    index = floor(clamp(pixel.b / (1.0 / 200.0), 0.0, 199.0));\n"
            + "    pixel.b = clamp(texture2D(curvesImage, vec2(1.0 / 200.0 * index, 0)).b, 0.0, 1.0);\n"
            + "    return pixel;\n"
            + "}\n"
            + "\n"
            + "highp vec3 fadeAdjust(highp vec3 color, highp float fadeVal) {\n"
            + "    return (color * (1.0 - fadeVal)) + ((color + (vec3(-0.9772) * pow(vec3(color), vec3(3.0)) + vec3(1.708) * pow(vec3(color), vec3(2.0)) + vec3(-0.1603) * vec3(color) + vec3(0.2878) - color * vec3(0.9))) * fadeVal);\n"
            + "}\n"
            + "\n"
            + "lowp vec3 tintRaiseShadowsCurve(lowp vec3 color) {\n"
            + "    return vec3(-0.003671) * pow(color, vec3(3.0)) + vec3(0.3842) * pow(color, vec3(2.0)) + vec3(0.3764) * color + vec3(0.2515);\n"
            + "}\n"
            + "\n"
            + "lowp vec3 tintShadows(lowp vec3 texel, lowp vec3 tintColor, lowp float tintAmount) {\n"
            + "    return clamp(mix(texel, mix(texel, tintRaiseShadowsCurve(texel), tintColor), tintAmount), 0.0, 1.0);\n"
            + "}\n"
            + "\n"
            + "lowp vec3 tintHighlights(lowp vec3 texel, lowp vec3 tintColor, lowp float tintAmount) {\n"
            + "    return clamp(mix(texel, mix(texel, vec3(1.0) - tintRaiseShadowsCurve(vec3(1.0) - texel), (vec3(1.0) - tintColor)), tintAmount), 0.0, 1.0);\n"
            + "}\n"
            + "\n"
            + "highp vec4 rnm(in highp vec2 tc) {\n"
            + "    highp float noise = sin(dot(tc, vec2(12.9898, 78.233))) * 43758.5453;\n"
            + "    return vec4(fract(noise), fract(noise * 1.2154), fract(noise * 1.3453), fract(noise * 1.3647)) * 2.0 - 1.0;\n"
            + "}\n"
            + "\n"
            + "highp float fade(in highp float t) {\n"
            + "    return t * t * t * (t * (t * 6.0 - 15.0) + 10.0);\n"
            + "}\n"
            + "\n"
            + "highp float pnoise3D(in highp vec3 p) {\n"
            + "    highp vec3 pi = permTexUnit * floor(p) + permTexUnitHalf;\n"
            + "    highp vec3 pf = fract(p);\n"
            + "    highp float perm = rnm(pi.xy).a;\n"
            + "    highp float n000 = dot(rnm(vec2(perm, pi.z)).rgb * 4.0 - 1.0, pf);\n"
            + "    highp float n001 = dot(rnm(vec2(perm, pi.z + permTexUnit)).rgb * 4.0 - 1.0, pf - vec3(0.0, 0.0, 1.0));\n"
            + "    perm = rnm(pi.xy + vec2(0.0, permTexUnit)).a;\n"
            + "    highp float n010 = dot(rnm(vec2(perm, pi.z)).rgb * 4.0 - 1.0, pf - vec3(0.0, 1.0, 0.0));\n"
            + "    highp float n011 = dot(rnm(vec2(perm, pi.z + permTexUnit)).rgb * 4.0 - 1.0, pf - vec3(0.0, 1.0, 1.0));\n"
            + "    perm = rnm(pi.xy + vec2(permTexUnit, 0.0)).a;\n"
            + "    highp float n100 = dot(rnm(vec2(perm, pi.z)).rgb * 4.0 - 1.0, pf - vec3(1.0, 0.0, 0.0));\n"
            + "    highp float n101 = dot(rnm(vec2(perm, pi.z + permTexUnit)).rgb * 4.0 - 1.0, pf - vec3(1.0, 0.0, 1.0));\n"
            + "    perm = rnm(pi.xy + vec2(permTexUnit, permTexUnit)).a;\n"
            + "    highp float n110 = dot(rnm(vec2(perm, pi.z)).rgb * 4.0 - 1.0, pf - vec3(1.0, 1.0, 0.0));\n"
            + "    highp float n111 = dot(rnm(vec2(perm, pi.z + permTexUnit)).rgb * 4.0 - 1.0, pf - vec3(1.0, 1.0, 1.0));\n"
            + "    highp vec4 n_x = mix(vec4(n000, n001, n010, n011), vec4(n100, n101, n110, n111), fade(pf.x));\n"
            + "    highp vec2 n_xy = mix(n_x.xy, n_x.zw, fade(pf.y));\n"
            + "    return mix(n_xy.x, n_xy.y, fade(pf.z));\n"
            + "}\n"
            + "\n"
            + "lowp vec2 coordRot(in lowp vec2 tc, in lowp float angle) {\n"
            + "    return vec2(((tc.x * 2.0 - 1.0) * cos(angle) - (tc.y * 2.0 - 1.0) * sin(angle)) * 0.5 + 0.5,\n"
            + "                ((tc.y * 2.0 - 1.0) * cos(angle) + (tc.x * 2.0 - 1.0) * sin(angle)) * 0.5 + 0.5);\n"
            + "}\n"
            + "\n"
            + "void main() {\n"
            + "    lowp vec4 source = texture2D(sTexture, vTextureCoord);\n"
            + "    lowp vec4 result = source;\n"
            + "    const lowp float toolEpsilon = 0.005;\n"
            + "\n"
            + "    if (skipTone < toolEpsilon) {\n"
            + "        result = vec4(applyRGBCurve(hslToRgb(applyLuminanceCurve(rgbToHsl(result.rgb)))), result.a);\n"
            + "    }\n"
            + "\n"
            + "    mediump float hsLuminance = dot(result.rgb, hsLuminanceWeighting);\n"
            + "    mediump float shadow = clamp((pow(hsLuminance, 1.0 / shadows) + (-0.76) * pow(hsLuminance, 2.0 / shadows)) - hsLuminance, 0.0, 1.0);\n"
            + "    mediump float highlight = clamp((1.0 - (pow(1.0 - hsLuminance, 1.0 / (2.0 - highlights)) + (-0.8) * pow(1.0 - hsLuminance, 2.0 / (2.0 - highlights)))) - hsLuminance, -1.0, 0.0);\n"
            + "    lowp vec3 hsresult = vec3(0.0, 0.0, 0.0) + ((hsLuminance + shadow + highlight) - 0.0) * ((result.rgb - vec3(0.0, 0.0, 0.0)) / (hsLuminance - 0.0));\n"
            + "\n"
            + "    mediump float contrastedLuminance = ((hsLuminance - 0.5) * 1.5) + 0.5;\n"
            + "    mediump float whiteInterp = contrastedLuminance * contrastedLuminance * contrastedLuminance;\n"
            + "    mediump float whiteTarget = clamp(highlights, 1.0, 2.0) - 1.0;\n"
            + "    hsresult = mix(hsresult, vec3(1.0), whiteInterp * whiteTarget);\n"
            + "    mediump float invContrastedLuminance = 1.0 - contrastedLuminance;\n"
            + "    mediump float blackInterp = invContrastedLuminance * invContrastedLuminance * invContrastedLuminance;\n"
            + "    mediump float blackTarget = 1.0 - clamp(shadows, 0.0, 1.0);\n"
            + "    hsresult = mix(hsresult, vec3(0.0), blackInterp * blackTarget);\n"
            + "    result = vec4(hsresult.rgb, result.a);\n"
            + "\n"
            + "    result = vec4(clamp(((result.rgb - vec3(0.5)) * contrast + vec3(0.5)), 0.0, 1.0), result.a);\n"
            + "\n"
            + "    if (abs(fadeAmount) > toolEpsilon) {\n"
            + "        result.rgb = fadeAdjust(result.rgb, fadeAmount);\n"
            + "    }\n"
            + "\n"
            + "    lowp float satLuminance = dot(result.rgb, satLuminanceWeighting);\n"
            + "    lowp vec3 greyScaleColor = vec3(satLuminance);\n"
            + "    result = vec4(clamp(mix(greyScaleColor, result.rgb, saturation), 0.0, 1.0), result.a);\n"
            + "\n"
            + "    if (abs(shadowsTintIntensity) > toolEpsilon) {\n"
            + "        result.rgb = tintShadows(result.rgb, shadowsTintColor, shadowsTintIntensity * 2.0);\n"
            + "    }\n"
            + "\n"
            + "    if (abs(highlightsTintIntensity) > toolEpsilon) {\n"
            + "        result.rgb = tintHighlights(result.rgb, highlightsTintColor, highlightsTintIntensity * 2.0);\n"
            + "    }\n"
            + "\n"
            + "    if (abs(exposure) > toolEpsilon) {\n"
            + "        mediump float mag = exposure * 1.045;\n"
            + "        mediump float exppower = 1.0 + abs(mag);\n"
            + "        if (mag < 0.0) { exppower = 1.0 / exppower; }\n"
            + "        result.r = 1.0 - pow((1.0 - result.r), exppower);\n"
            + "        result.g = 1.0 - pow((1.0 - result.g), exppower);\n"
            + "        result.b = 1.0 - pow((1.0 - result.b), exppower);\n"
            + "    }\n"
            + "\n"
            + "    if (abs(warmth) > toolEpsilon) {\n"
            + "        highp vec3 yuvVec;\n"
            + "        if (warmth > 0.0) {\n"
            + "            yuvVec = vec3(0.1765, -0.1255, 0.0902);\n"
            + "        } else {\n"
            + "            yuvVec = -vec3(0.0588, 0.1569, -0.1255);\n"
            + "        }\n"
            + "        highp vec3 yuvColor = rgbToYuv(result.rgb);\n"
            + "        highp float luma = yuvColor.r;\n"
            + "        highp float curveScale = sin(luma * 3.14159);\n"
            + "        yuvColor += 0.375 * warmth * curveScale * yuvVec;\n"
            + "        result.rgb = yuvToRgb(yuvColor);\n"
            + "    }\n"
            + "\n"
            + "    if (abs(grain) > toolEpsilon) {\n"
            + "        highp vec3 rotOffset = vec3(1.425, 3.892, 5.835);\n"
            + "        highp vec2 rotCoordsR = coordRot(vTextureCoord, rotOffset.x);\n"
            + "        highp vec3 noise = vec3(pnoise3D(vec3(rotCoordsR * vec2(width / grainsize, height / grainsize), 0.0)));\n"
            + "        lowp vec3 lumcoeff = vec3(0.299, 0.587, 0.114);\n"
            + "        lowp float luminance = dot(result.rgb, lumcoeff);\n"
            + "        lowp float lum = smoothstep(0.2, 0.0, luminance);\n"
            + "        lum += luminance;\n"
            + "        noise = mix(noise, vec3(0.0), pow(lum, 4.0));\n"
            + "        result.rgb = result.rgb + noise * grain;\n"
            + "    }\n"
            + "\n"
            + "    if (abs(vignette) > toolEpsilon) {\n"
            + "        const lowp float midpoint = 0.7;\n"
            + "        const lowp float fuzziness = 0.62;\n"
            + "        lowp float radDist = length(vTextureCoord - 0.5) / sqrt(0.5);\n"
            + "        lowp float mag = easeInOutSigmoid(radDist * midpoint, fuzziness) * vignette * 0.645;\n"
            + "        result.rgb = mix(pow(result.rgb, vec3(1.0 / (1.0 - mag))), vec3(0.0), mag * mag);\n"
            + "    }\n"
            + "\n"
            + "    gl_FragColor = result;\n"
            + "}\n";

    public static final String RADIAL_BLUR_FRAGMENT = ""
            + "varying highp vec2 vTextureCoord;\n"
            + "uniform sampler2D sTexture;\n"
            + "uniform sampler2D inputImageTexture2;\n"
            + "uniform lowp float excludeSize;\n"
            + "uniform lowp vec2 excludePoint;\n"
            + "uniform lowp float excludeBlurSize;\n"
            + "uniform highp float aspectRatio;\n"
            + "void main() {\n"
            + "    lowp vec4 sharpImageColor = texture2D(sTexture, vTextureCoord);\n"
            + "    lowp vec4 blurredImageColor = texture2D(inputImageTexture2, vTextureCoord);\n"
            + "    highp vec2 texCoordToUse = vec2(vTextureCoord.x, (vTextureCoord.y * aspectRatio + 0.5 - 0.5 * aspectRatio));\n"
            + "    highp float distanceFromCenter = distance(excludePoint, texCoordToUse);\n"
            + "    gl_FragColor = mix(sharpImageColor, blurredImageColor, smoothstep(excludeSize - excludeBlurSize, excludeSize, distanceFromCenter));\n"
            + "}\n";

    public static final String LINEAR_BLUR_FRAGMENT = ""
            + "varying highp vec2 vTextureCoord;\n"
            + "uniform sampler2D sTexture;\n"
            + "uniform sampler2D inputImageTexture2;\n"
            + "uniform lowp float excludeSize;\n"
            + "uniform lowp vec2 excludePoint;\n"
            + "uniform lowp float excludeBlurSize;\n"
            + "uniform highp float angle;\n"
            + "uniform highp float aspectRatio;\n"
            + "void main() {\n"
            + "    lowp vec4 sharpImageColor = texture2D(sTexture, vTextureCoord);\n"
            + "    lowp vec4 blurredImageColor = texture2D(inputImageTexture2, vTextureCoord);\n"
            + "    highp vec2 texCoordToUse = vec2(vTextureCoord.x, (vTextureCoord.y * aspectRatio + 0.5 - 0.5 * aspectRatio));\n"
            + "    highp float distanceFromCenter = abs((texCoordToUse.x - excludePoint.x) * aspectRatio * cos(angle) + (texCoordToUse.y - excludePoint.y) * sin(angle));\n"
            + "    gl_FragColor = mix(sharpImageColor, blurredImageColor, smoothstep(excludeSize - excludeBlurSize, excludeSize, distanceFromCenter));\n"
            + "}\n";
}
